export let keyArr;
export let productList = [
  {
    id: 1.1001,
    desEng: `Classic Beef Biryani`,
    desBangla: "ক্লাসিক বিফ বিরিয়ানি।",
    price: 350,
    image: `https://i.postimg.cc/sgZzKSQP/biryani.jpg`,
    category: `main`,
    color: [[`brown`, `https://i.postimg.cc/DyFtQLKz/biryani.jpg`]],
    longDes: `A flavorful and aromatic biryani made with tender beef, basmati rice, and a blend of premium spices.`,
    keyword: `biryani`,
    weight: `750g`,
  },
  {
    id: 1.1002,
    desEng: `Crispy Fried Hilsa`,
    desBangla: "মচমচে ইলিশ মাছ ভাজা।",
    price: 450,
    image: `https://i.postimg.cc/CL2YjJ1L/hilsa.jpg`,
    category: `main`,
    color: [[`golden`, `https://i.postimg.cc/qMJgZySc/hilsa.jpg`]],
    longDes: `Fresh Hilsa fish, fried to a crispy perfection with traditional spices. 
Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere maiores cum quis rerum iure nulla ducimus, error, ipsa explicabo ex, odio eaque minus eos consequuntur id. Tempora incidunt cumque, inventore maxime quis, libero deleniti hic animi, non nemo labore accusantium! Nemo qui sapiente maxime modi ipsa nihil id officia dignissimos!
`,
    keyword: `hilsa`,
    weight: `500g`,
  },
  {
    id: 1.1003,
    desEng: `Juicy Chicken Burger`,
    desBangla: "জুসি চিকেন বার্গার।",
    price: 180,
    image: `https://i.postimg.cc/mrYsWsSt/burger.jpg`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/RFY51T9H/burger.jpg`]],
    longDes: `A juicy chicken patty topped with fresh veggies and creamy sauce, served in a toasted bun.`,
    keyword: `burger`,
    weight: `300g`,
  },
  {
    id: 1.1004,
    desEng: `Handmade Italian Pizza`,
    desBangla: "হাতের তৈরি ইতালিয়ান পিজ্জা।",
    price: 300,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/cJd44vLf/1001.jpg`]],
    longDes: `Authentic Italian pizza made with fresh dough, tangy tomato sauce, and premium cheese.`,
    keyword: `pizza`,
    weight: `500g`,
  },
  {
    id: 1.1005,
    desEng: `Spicy Fried Chicken`,
    desBangla: "মসলাদার ফ্রাইড চিকেন।",
    price: 200,
    image: `https://i.postimg.cc/NFzhkfQP/chicken-fry.jpg`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/k4k0LqJq/fried-chicken.jpg`]],
    longDes: `Crispy and spicy fried chicken, seasoned with a unique blend of spices.`,
    keyword: `fried`,
    weight: `300g`,
  },
  {
    id: 1.1006,
    desEng: `Crispy`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 120,
    image: `https://i.postimg.cc/zBq1Jcdp/capacuno.jpg`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/QNSYHJVR/french-fries.jpg`]],
    longDes: `Golden crispy French fries, perfect as a snack or side dish.`,
    keyword: `french fries,crispy,snack`,
    weight: `200g`,
  },
  {
    id: 1.1007,
    desEng: `Cheesy Pasta`,
    desBangla: "চিজি পাস্তা।",
    price: 250,
    image: `https://i.postimg.cc/43kg0dVD/pasta.jpg`,
    category: `main`,
    color: [[`white`, `https://i.postimg.cc/T1p1xR5X/pasta.jpg`]],
    longDes: `Creamy and cheesy pasta with a rich, velvety sauce and fresh herbs.`,
    keyword: `pasta`,
    weight: `400g`,
  },
  {
    id: 1.1008,
    desEng: `Mexican`,
    desBangla: "মেক্সিকান ট্যাকোস।",
    price: 300,
    image: `https://i.postimg.cc/8c5Qvrg6/tacos.jpg`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/pTfHzR8z/tacos.jpg`]],
    longDes: `Traditional Mexican tacos filled with spicy meat, fresh veggies, and tangy sauce.`,
    keyword: `tacos`,
    weight: `350g`,
  },
  {
    id: 1.1001,
    desEng: `Classic Beef Biryani`,
    desBangla: "ক্লাসিক বিফ বিরিয়ানি।",
    price: 350,
    image: `https://i.postimg.cc/sgZzKSQP/biryani.jpg`,
    category: `main`,
    color: [[`brown`, `https://i.postimg.cc/DyFtQLKz/biryani.jpg`]],
    longDes: `A flavorful and aromatic biryani made with tender beef, basmati rice, and a blend of premium spices.`,
    keyword: `biryani`,
    weight: `750g`,
  },
  {
    id: 1.1002,
    desEng: `Crispy Fried Hilsa`,
    desBangla: "মচমচে ইলিশ মাছ ভাজা।",
    price: 450,
    image: `https://i.postimg.cc/CL2YjJ1L/hilsa.jpg`,
    category: `main`,
    color: [[`golden`, `https://i.postimg.cc/qMJgZySc/hilsa.jpg`]],
    longDes: `Fresh Hilsa fish, fried to a crispy perfection with traditional spices. 
Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere maiores cum quis rerum iure nulla ducimus, error, ipsa explicabo ex, odio eaque minus eos consequuntur id. Tempora incidunt cumque, inventore maxime quis, libero deleniti hic animi, non nemo labore accusantium! Nemo qui sapiente maxime modi ipsa nihil id officia dignissimos!
`,
    keyword: `hilsa`,
    weight: `500g`,
  },
  {
    id: 1.1003,
    desEng: `Juicy Chicken Burger`,
    desBangla: "জুসি চিকেন বার্গার।",
    price: 180,
    image: `https://i.postimg.cc/mrYsWsSt/burger.jpg`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/RFY51T9H/burger.jpg`]],
    longDes: `A juicy chicken patty topped with fresh veggies and creamy sauce, served in a toasted bun.`,
    keyword: `burger`,
    weight: `300g`,
  },
  {
    id: 1.1004,
    desEng: `Handmade Italian Pizza`,
    desBangla: "হাতের তৈরি ইতালিয়ান পিজ্জা।",
    price: 300,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/cJd44vLf/1001.jpg`]],
    longDes: `Authentic Italian pizza made with fresh dough, tangy tomato sauce, and premium cheese.`,
    keyword: `pizza`,
    weight: `500g`,
  },
  {
    id: 1.1005,
    desEng: `Spicy Fried Chicken`,
    desBangla: "মসলাদার ফ্রাইড চিকেন।",
    price: 200,
    image: `https://i.postimg.cc/NFzhkfQP/chicken-fry.jpg`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/k4k0LqJq/fried-chicken.jpg`]],
    longDes: `Crispy and spicy fried chicken, seasoned with a unique blend of spices.`,
    keyword: `fried`,
    weight: `300g`,
  },
  {
    id: 1.1006,
    desEng: `Crispy`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 120,
    image: `https://i.postimg.cc/zBq1Jcdp/capacuno.jpg`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/QNSYHJVR/french-fries.jpg`]],
    longDes: `Golden crispy French fries, perfect as a snack or side dish.`,
    keyword: `french fries,crispy,snack`,
    weight: `200g`,
  },
  {
    id: 1.1007,
    desEng: `Cheesy Pasta`,
    desBangla: "চিজি পাস্তা।",
    price: 250,
    image: `https://i.postimg.cc/43kg0dVD/pasta.jpg`,
    category: `main`,
    color: [[`white`, `https://i.postimg.cc/T1p1xR5X/pasta.jpg`]],
    longDes: `Creamy and cheesy pasta with a rich, velvety sauce and fresh herbs.`,
    keyword: `pasta`,
    weight: `400g`,
  },
  {
    id: 1.1008,
    desEng: `Mexican`,
    desBangla: "মেক্সিকান ট্যাকোস।",
    price: 300,
    image: `https://i.postimg.cc/8c5Qvrg6/tacos.jpg`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/pTfHzR8z/tacos.jpg`]],
    longDes: `Traditional Mexican tacos filled with spicy meat, fresh veggies, and tangy sauce.`,
    keyword: `tacos`,
    weight: `350g`,
  },
  {
    id: 1.1001,
    desEng: `Classic Beef Biryani`,
    desBangla: "ক্লাসিক বিফ বিরিয়ানি।",
    price: 350,
    image: `https://i.postimg.cc/sgZzKSQP/biryani.jpg`,
    category: `main`,
    color: [[`brown`, `https://i.postimg.cc/DyFtQLKz/biryani.jpg`]],
    longDes: `A flavorful and aromatic biryani made with tender beef, basmati rice, and a blend of premium spices.`,
    keyword: `biryani`,
    weight: `750g`,
  },
  {
    id: 1.1002,
    desEng: `Crispy Fried Hilsa`,
    desBangla: "মচমচে ইলিশ মাছ ভাজা।",
    price: 450,
    image: `https://i.postimg.cc/CL2YjJ1L/hilsa.jpg`,
    category: `main`,
    color: [[`golden`, `https://i.postimg.cc/qMJgZySc/hilsa.jpg`]],
    longDes: `Fresh Hilsa fish, fried to a crispy perfection with traditional spices. 
Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere maiores cum quis rerum iure nulla ducimus, error, ipsa explicabo ex, odio eaque minus eos consequuntur id. Tempora incidunt cumque, inventore maxime quis, libero deleniti hic animi, non nemo labore accusantium! Nemo qui sapiente maxime modi ipsa nihil id officia dignissimos!
`,
    keyword: `hilsa`,
    weight: `500g`,
  },
  {
    id: 1.1003,
    desEng: `Juicy Chicken Burger`,
    desBangla: "জুসি চিকেন বার্গার।",
    price: 180,
    image: `https://i.postimg.cc/mrYsWsSt/burger.jpg`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/RFY51T9H/burger.jpg`]],
    longDes: `A juicy chicken patty topped with fresh veggies and creamy sauce, served in a toasted bun.`,
    keyword: `burger`,
    weight: `300g`,
  },
  {
    id: 1.1004,
    desEng: `Handmade Italian Pizza`,
    desBangla: "হাতের তৈরি ইতালিয়ান পিজ্জা।",
    price: 300,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/cJd44vLf/1001.jpg`]],
    longDes: `Authentic Italian pizza made with fresh dough, tangy tomato sauce, and premium cheese.`,
    keyword: `pizza`,
    weight: `500g`,
  },
  {
    id: 1.1005,
    desEng: `Spicy Fried Chicken`,
    desBangla: "মসলাদার ফ্রাইড চিকেন।",
    price: 200,
    image: `https://i.postimg.cc/NFzhkfQP/chicken-fry.jpg`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/k4k0LqJq/fried-chicken.jpg`]],
    longDes: `Crispy and spicy fried chicken, seasoned with a unique blend of spices.`,
    keyword: `fried`,
    weight: `300g`,
  },
  {
    id: 1.1006,
    desEng: `Crispy`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 120,
    image: `https://i.postimg.cc/zBq1Jcdp/capacuno.jpg`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/QNSYHJVR/french-fries.jpg`]],
    longDes: `Golden crispy French fries, perfect as a snack or side dish.`,
    keyword: `french fries,crispy,snack`,
    weight: `200g`,
  },
  {
    id: 1.1007,
    desEng: `Cheesy Pasta`,
    desBangla: "চিজি পাস্তা।",
    price: 250,
    image: `https://i.postimg.cc/43kg0dVD/pasta.jpg`,
    category: `main`,
    color: [[`white`, `https://i.postimg.cc/T1p1xR5X/pasta.jpg`]],
    longDes: `Creamy and cheesy pasta with a rich, velvety sauce and fresh herbs.`,
    keyword: `pasta`,
    weight: `400g`,
  },
  {
    id: 1.1008,
    desEng: `Mexican`,
    desBangla: "মেক্সিকান ট্যাকোস।",
    price: 300,
    image: `https://i.postimg.cc/8c5Qvrg6/tacos.jpg`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/pTfHzR8z/tacos.jpg`]],
    longDes: `Traditional Mexican tacos filled with spicy meat, fresh veggies, and tangy sauce.`,
    keyword: `tacos`,
    weight: `350g`,
  },
  {
    id: 1.1001,
    desEng: `Classic Beef Biryani`,
    desBangla: "ক্লাসিক বিফ বিরিয়ানি।",
    price: 350,
    image: `https://i.postimg.cc/sgZzKSQP/biryani.jpg`,
    category: `main`,
    color: [[`brown`, `https://i.postimg.cc/DyFtQLKz/biryani.jpg`]],
    longDes: `A flavorful and aromatic biryani made with tender beef, basmati rice, and a blend of premium spices.`,
    keyword: `biryani`,
    weight: `750g`,
  },
  {
    id: 1.1002,
    desEng: `Crispy Fried Hilsa`,
    desBangla: "মচমচে ইলিশ মাছ ভাজা।",
    price: 450,
    image: `https://i.postimg.cc/CL2YjJ1L/hilsa.jpg`,
    category: `main`,
    color: [[`golden`, `https://i.postimg.cc/qMJgZySc/hilsa.jpg`]],
    longDes: `Fresh Hilsa fish, fried to a crispy perfection with traditional spices. 
Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere maiores cum quis rerum iure nulla ducimus, error, ipsa explicabo ex, odio eaque minus eos consequuntur id. Tempora incidunt cumque, inventore maxime quis, libero deleniti hic animi, non nemo labore accusantium! Nemo qui sapiente maxime modi ipsa nihil id officia dignissimos!
`,
    keyword: `hilsa`,
    weight: `500g`,
  },
  {
    id: 1.1003,
    desEng: `Juicy Chicken Burger`,
    desBangla: "জুসি চিকেন বার্গার।",
    price: 180,
    image: `https://i.postimg.cc/mrYsWsSt/burger.jpg`,
    category: `snack`,
    color: [[`yellow`, `https://i.postimg.cc/RFY51T9H/burger.jpg`]],
    longDes: `A juicy chicken patty topped with fresh veggies and creamy sauce, served in a toasted bun.`,
    keyword: `burger`,
    weight: `300g`,
  },
  {
    id: 1.1004,
    desEng: `Handmade Italian Pizza`,
    desBangla: "হাতের তৈরি ইতালিয়ান পিজ্জা।",
    price: 300,
    image: `https://i.postimg.cc/50Sds2r4/1001.webp`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/cJd44vLf/1001.jpg`]],
    longDes: `Authentic Italian pizza made with fresh dough, tangy tomato sauce, and premium cheese.`,
    keyword: `pizza`,
    weight: `500g`,
  },
  {
    id: 1.1005,
    desEng: `Spicy Fried Chicken`,
    desBangla: "মসলাদার ফ্রাইড চিকেন।",
    price: 200,
    image: `https://i.postimg.cc/NFzhkfQP/chicken-fry.jpg`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/k4k0LqJq/fried-chicken.jpg`]],
    longDes: `Crispy and spicy fried chicken, seasoned with a unique blend of spices.`,
    keyword: `fried`,
    weight: `300g`,
  },
  {
    id: 1.1006,
    desEng: `Crispy`,
    desBangla: "মচমচে ফ্রেঞ্চ ফ্রাই।",
    price: 120,
    image: `https://i.postimg.cc/zBq1Jcdp/capacuno.jpg`,
    category: `snack`,
    color: [[`golden`, `https://i.postimg.cc/QNSYHJVR/french-fries.jpg`]],
    longDes: `Golden crispy French fries, perfect as a snack or side dish.`,
    keyword: `french fries,crispy,snack`,
    weight: `200g`,
  },
  {
    id: 1.1007,
    desEng: `Cheesy Pasta`,
    desBangla: "চিজি পাস্তা।",
    price: 250,
    image: `https://i.postimg.cc/43kg0dVD/pasta.jpg`,
    category: `main`,
    color: [[`white`, `https://i.postimg.cc/T1p1xR5X/pasta.jpg`]],
    longDes: `Creamy and cheesy pasta with a rich, velvety sauce and fresh herbs.`,
    keyword: `pasta`,
    weight: `400g`,
  },
  {
    id: 1.1008,
    desEng: `Mexican`,
    desBangla: "মেক্সিকান ট্যাকোস।",
    price: 300,
    image: `https://i.postimg.cc/8c5Qvrg6/tacos.jpg`,
    category: `snack`,
    color: [[`red`, `https://i.postimg.cc/pTfHzR8z/tacos.jpg`]],
    longDes: `Traditional Mexican tacos filled with spicy meat, fresh veggies, and tangy sauce.
    1. solayman is a good boy.
    2. nasim talk with his gf (temporary).
    3. salman is a fool but good boy.
        4. solayman is a good boy.
    5. nasim talk with his gf (temporary).
    6. salman is a fool but good boy.
        7. solayman is a good boy.
    8. nasim talk with his gf (temporary).
    9. salman is a fool but good boy.
    `,
    keyword: `tacos`,
    weight: `350g`,
  },
];
/**
 * The functoin make the unique key word array
 * @param {*} data
 * @returns
 */

// Generate unique keywords array
let uniqueKeywords = [
  ...new Set(
    productList
      .flatMap((product) => product.keyword.split(","))
      .map((keyword) => keyword.trim().toLowerCase())
  ),
];
keyArr = uniqueKeywords;

// tempo
const newLongDes = `Traditional Mexican tacos filled with spicy meat, fresh veggies, and tangy sauce.
1. Solayman is a good boy.
2. Nasim talk with his gf (temporary).
3. Salman is a fool but good boy.
4. Solayman is a good boy.
5. Nasim talk with his gf (temporary).
6. Salman is a fool but good boy.
7. Solayman is a good boy.
8. Nasim talk with his gf (temporary).
9. Salman is a fool but good boy.`;

productList.forEach((item) => {
  item.longDes = newLongDes;
});
